### ISSUE TITLE
no error handling for failed log delivery

### ISSUE THREAD

**Issue by YafetMelake** [ismaeelbashir03/Log-A-Rythm#1]
If delivery to the backend fails, ELK stack for example, there is no fallback or retry or anything. This is annoying because when i was trying to implement it I didnt know if it was working properly and couldn't track the lost logs.
Do you know when this will be updated? Maybe you could a local buffer and retry logic or just notify when it fails to deliver

**Comment by ismaeelbashir03** [comment]
We are not fully using the ELK stack, if you **looked** at the repository you would know that we replace some components for our own simpler implementations, which makes it easier to use. Unfortunately, we do not have custom recovery methods as we had to make this in 12 hours. I will make note to add this in the future :)

**Comment by YafetMelake** [comment]
I did and I am currently using it. I am spinning it off for more complex implementations and "noting it for future" is not a solution. 12hrs or 12 days (skill issue) need to be able to track lost logs
